### ISSUE TITLE
setMasterPolicyTimeoutWhenDebuggerAttached does nothing

### ISSUE THREAD

**Issue by vbevans94** [android/android-test#1029] opened 2021-08-05 10:15 UTC
### Description
Looks like timeoutWhenDebuggerAttached parameter is not used.
```
/**
   * This method overrides Espresso's default behaviour of disabling timeouts when a step debugger
   * is attached to the VM. Setting the timeout flag reenables the behaviour of throwing a timeout
   * exception.
   *
   * <p>The value set in this method is superceded if {@link #unsafeMakeMasterPolicyWarning()} is
   * also called.
   */
  public static void setMasterPolicyTimeoutWhenDebuggerAttached(
      boolean timeoutWhenDebuggerAttached) {
    masterIdlingPolicy =
        masterIdlingPolicy
            .toBuilder()
            .build();
  }
```

### Steps to Reproduce
Call
```
IdlingPolicies.setMasterPolicyTimeoutWhenDebuggerAttached(false)
```

### Expected Results
Test doesn't fail with timeout with attached debugger.

### Actual Results
Test still fails with attached debugger.

### AndroidX Test and Android OS Versions
androidx.test.espresso:espresso-core:3.3.0
Android API 28

**Comment by TWiStErRob** [comment] 2021-08-06 07:58
Duplicate of #814, fixed by #828 in 1.4.0+

**Closed** 2021-10-04 20:25 UTC
