### ISSUE TITLE
How to verify Toast is displayed by Espresso from Android 11

### ISSUE THREAD

**Issue by testfacefanpage** [android/android-test#1559] opened 2022-10-21 08:29 UTC
Hello everyone, does anyone have idea how to verify Toast is displayed by Espresso from Android 11. For Android lower 11, we often write something like this and it works fine.

Espresso.onView(withText("Toast message here"))
                .inRoot(withDecorView(not(decorView)))
                .check(matches(isDisplayed()))

Thank you all for your idea about that.

**Comment by ralf-at-android** [comment] 2022-10-21 18:14
Hi, I haven't tried on Android 11. For the sake of completeness, what is the issue you experience? Please indicate how it fails.

**Comment by ralf-at-android** [comment] 2022-10-21 19:15
Duplicate of https://github.com/android/android-test/issues/803

**Closed by ralf-at-android** 2022-10-21 19:15 UTC
