### ISSUE TITLE
Allow Launching a FragmentScenario within a given ActivityScenario

### ISSUE THREAD

**Issue by osamarao** [android/android-test#242] opened 2019-03-12 13:56 UTC
After launching an `ActivityScenario` in this manner I can assert on which fragment should be showing
`ActivityScenario<MainActivity> scenario = ActivityScenario.launch(someIntent()));`
```
scenario.onActivity(activity -> {
assertThat(activity.getSupportFragmentManager().getFragments().contains(new SomeFragment())).isTrue();
        });
```

Can `SomeFragment` be launched as a `FragmentScenario` while contained in the launched `ActivityScenario` so that `SomeFragment` can be driven to start another fragment?

**Comment by yuuki3655** [comment] 2019-03-13 01:11
FragmentScenario is designed for testing Fragment in isolation, so we intentionally made ActivityScenario a private member in FragmentScenario.

The test scenario you explained sounds like an integration test between three components, Activity, SomeFragment, and the other Fragment. We recommend using ActivityScenario for this type of tests as there is a dependency to the hosting Activity. Your code snippet looks good to me.

Let me close this as intended behavior. Feel free to reopen if I miss anything.

**Closed by yuuki3655** 2019-03-13 01:11 UTC
